export class Constants {

    public static readonly ACT_STS = 'actionStatus';
    public static readonly ADM_SXS = 'Admin Login Success';
    public static readonly ADMIN = "A";
    public static readonly AMENITY_REQ_SXS = 'Amenity Request Success';
    public static readonly AMNT_CRT_FAIL = "Amenity Creation Failure";
    public static readonly AMNT_CRT_SXS = "Amenity Creation Success";
    public static readonly AMNT_RQST_FAIL = "Amenity Request Failure";
    public static readonly AMNT_RQST_SXS = "Amenity Request Success";
    public static readonly CUST_REG_FAIL = "Customer Registration Failed";
    public static readonly CUST_REG_SXS = "Customer Registration Success";
    public static readonly CUST_SXS = 'Customer Login Success';
    public static readonly CUSTOMER = "C";
    public static readonly EMP_CRT_FAIL = "Employee Creation Failure";
    public static readonly EMP_CRT_SXS = "Employee Creation Success";
    public static readonly EMP_SXS = 'Employee Login Success';
    public static readonly EMPLOYEE = "E";
    public static readonly EXCEPTION_OCCURED = "Exception Occured";
    public static readonly FAILURE = "failure"
    public static readonly GENDER = 'GENDER';
    public static readonly GUEST_COUNT = 'GUEST_COUNT';
    public static readonly LOCATION = 'LOCATION';
    public static readonly LOOKUP_SAVE_SXS = "Lookups Save Success";
    public static readonly OCCUPIED = 'occupied';
    public static readonly REG_FLR = 'Registration Failed';
    public static readonly REG_SXS = 'Registration Success';
    public static readonly RM_CRT_FAIL = "Room Creation Failed";
    public static readonly RM_CRT_SXS = "Room Creation Success";
    public static readonly ROM_REG_DLR = 'Room Registration Failed';
    public static readonly ROM_REG_SXS = 'Room Registration Success';
    public static readonly ROOM_BOOK_FAIL = "Room Booking Failed";
    public static readonly ROOM_BOOK_SXS = "Room Booking Success";
    public static readonly ROOM_CATEGORY = 'ROOM_CATEGORY';
    public static readonly ROOM_MODEL = 'ROOM_MODEL';
    public static readonly ROOM_TYPE = 'ROOM_TYPE';
    public static readonly STS_MSG = 'statusMessage';
    public static readonly SUCCESS = "success";
    public static readonly TOUR_BOOK_SXS = 'Tour Package Booking Success';
    public static readonly TOUR_DURATION = 'TOUR_DURATION';
    public static readonly TOUR_PKG_BOOK_FAIL = "Tour Package Booking Failed";
    public static readonly TOUR_PKG_BOOK_SXS = "Tour Package Booking Success";
    public static readonly TOUR_PKG_CRT_FAIL = "Tour Package Create Failure";
    public static readonly TOUR_PKG_CRT_SXS = "Tour Package Create Success";
    public static readonly TUR_PACK_SXS = 'Tour Package Creation Success';
    public static readonly VACANT = 'vacant';
}
